// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zdxwqutdjzcpdxouojgh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpkeHdxdXRkanpjcGR4b3VvamdoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzgzNzIwMzcsImV4cCI6MjA5Mzk0ODAzN30.8OU2D15IU5BHgTPnksd3ZSFemuVojVqESA8KrVjHLS8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});